version: '3'
services:
  # service discovery
  consul:
    image: consul
  # several APIs
  api-python:
    image: victor755555/api-python:latest
    depends_on:
      - consul 
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      - consul 
  # GraphQL entry to APIs
  entry:
    build: . 
    command: run begin
    image: victor755555/entry:latest
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    ports:
      - "8080:8080"
    depends_on:
      - consul 
