version: '2'
services:
  # service discovery
  consul:
    image: consul
  # several APIs
  api-ruby:
    image: victor755555/api-ruby:latest
    # for debuggin purposes 
    ports:
      - "4455:4567"
    command: "ruby languages.rb"
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      - consul
  api-python:
    image: victor755555/api-python:latest
    # for debuggin purposes 
    ports:
      - "4456:5000"
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    depends_on:
      - consul 
  # GraphQL entry to APIs
  entry:
    build: . 
    command: run begin
    image: victor755555/entry:latest
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    ports:
      - "8082:8080"
    depends_on:
      - consul 
